wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709185198.347059
    t:
      1:
      - 5
      - 53
      - 55
      - 95
      2:
      - 5
      - 53
      - 55
      - 95
      3:
      - 2
      - 23
      4: 3.11.7
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
